version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: swarm:0.0.1-SNAPSHOT
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - "8088:8088"
    networks:
      - webnet
networks:
  webnet: